name: WakaTime Readme

on:
  workflow_dispatch: # Manual workflow trigger
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme-languages:
    name: WakaTime Readme Language Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master # Action name
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

          # Content
          SHOW_TITLE: true
          SECTION_NAME: waka
          BLOCKS: ▱▰
          CODE_LANG: python
          TIME_RANGE: last_30_days
          LANG_COUNT: 5
          SHOW_TIME: true
          SHOW_TOTAL: true

          # Commit
          COMMIT_MESSAGE: Updated waka-readme graph
          TARGET_BRANCH: main
          TARGET_PATH: README.md
          COMMITTER_NAME: GitHubActionBot
          COMMITTER_EMAIL: action-bot@github.com
  
  update-readme-commits:
    name: GitHub Commits
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          # Config
          SECTION_NAME: commits
          SHOW_UPDATED_DATE: false

          # Content
          SHOW_LINES_OF_CODE: false
          SHOW_TOTAL_CODE_TIME: false
          SHOW_PROFILE_VIEWS: false
          SHOW_COMMIT: true
          SHOW_DAYS_OF_WEEK: false
          SHOW_LANGUAGE: false
          SHOW_OS: false
          SHOW_PROJECTS: false # Investigate to replicate languages format to show projects programming time
          SHOW_TIMEZONE: true
          SHOW_EDITORS: false
          SHOW_LANGUAGE_PER_REPO: false
          SHOW_SHORT_INFO: false
          SHOW_LOC_CHART: false          

          # Commit
          COMMIT_BY_ME: false
          COMMIT_USERNAME: GitHubActionBot
          COMMIT_EMAIL: action-bot@github.com
          
